name: Sync fastresp-server-web
     on:
       repository_dispatch:
         types: [sync]
     jobs:
       sync:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v3
             with:
               repository: fastcoltd/fastonline-doc
               token: ${{ secrets.PAT }}
           - name: "Sync fastresp-server-web"
             run: |
               git clone https://github.com/fastcoltd/fastresp-server-web.git temp
               rm -rf web/*
               cp -r temp/* web/
               find web -type f -name "*.html" -exec sed -i 's|href="css/|href="web/css/|g' {} \;
               find web -type f -name "*.html" -exec sed -i 's|src="js/|src="web/js/|g' {} \;
               find web -type f -name "*.css" -exec sed -i 's|url("images/|url("web/images/|g' {} \;
               git config user.name "Fastco Dev"
               git config user.email "dev@fastco.com"
               git add web
               git commit -m "Sync fastresp-server-web updates" || true
               git push
